import { Product } from './product.model';

export const PRODUCTS: Product[] = [
  {
    likes: 0,
    categoryId: 2,
    id: 1,
    name: 'SSD Kingston SA400S37 480GB',
    description: 'Надёжный SSD накопитель объёмом 480 ГБ для ускорения работы компьютера или ноутбука. Обеспечивает быструю загрузку системы, программ и игр. Отличный выбор для апгрейда старых устройств.',
    price: 45000,
    rating: 4.8,
    image: 'images/kingston.jpg',
    images: ['images/kingston1.jpg', 'images/kingston2.jpg', 'images/kingston3.jpg'],
    link: 'https://kaspi.kz/shop/p/ssd-kingston-sa400s37-480g-480-gb-6800659/',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 2,
    id: 2,
    name: 'Клавиатура Ultra-S ULTKB02-2 серый',
    description: 'Игровая клавиатура с RGB-подсветкой и мультимедийными клавишами. Подходит для работы и игр. Современный дизайн и удобная раскладка обеспечивают комфорт при длительном использовании.',
    price: 19997,
    rating: 4.6,
    image: 'images/klava.jpg',
    images: ['images/klava1.jpg', 'images/klava2.jpg', 'images/klava3.jpg'],
    link: 'https://kaspi.kz/shop/p/ultra-s-ultkb02-2-serii-146337554/',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 1,
    id: 3,
    name: 'Apple iPhone 17 Pro 256GB темно-синий',
    description: 'Флагманский смартфон Apple с мощным процессором и премиальным дизайном. Оснащён продвинутой камерой и ярким OLED-дисплеем. Подходит для фото, видео и повседневной работы.',
    price: 699990,
    rating: 4.9,
    image: 'images/iphone.jpg',
    images: ['images/iphone1.jpg', 'images/iphone2.jpg', 'images/iphone3.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-iphone-17-pro-256gb-temno-sinii-145438959/',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 2,
    id: 4,
    name: 'Чехол для Apple iPhone 17 Pro Max прозрачный',
    description: 'Прозрачный защитный чехол для iPhone 17 Pro Max. Надёжно защищает корпус от царапин и ударов. Лёгкий и удобный в использовании.',
    price: 4990,
    rating: 4.5,
    image: 'images/case.jpg',
    images: ['images/case1.jpg', 'images/case2.jpg', 'images/case3.jpg'],
    link: 'https://kaspi.kz/shop/p/chehol-dlja-apple-iphone-17-pro-max-prozrachnyi-145825236/',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 4,
    id: 5,
    name: 'Xiaomi Smart Band 10 черный',
    description: 'Умный фитнес-браслет для отслеживания активности и сна. Поддерживает уведомления, шагомер и мониторинг пульса. Компактный и удобный для ежедневного использования.',
    price: 19990,
    rating: 4.7,
    image: 'images/band.jpg',
    images: ['images/band1.jpg', 'images/band2.jpg', 'images/band3.jpg'],
    link: 'https://kaspi.kz/shop/p/xiaomi-smart-band-10-chernyi-141530632/',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 4,
    id: 6,
    name: 'IQOS Iluma i One голубой',
    description: 'Современное устройство для нагревания табака с компактным дизайном. Простое в использовании и удобное для повседневного применения. Стильный голубой корпус.',
    price: 29990,
    rating: 4.6,
    image: 'images/iqos.jpg',
    images: ['images/iqos1.jpg', 'images/iqos2.jpg', 'images/iqos3.jpg'],
    link: 'https://kaspi.kz/shop/p/iqos-iluma-i-one-goluboi-145958994/',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 4,
    id: 7,
    name: 'Lumo Aqua X серый',
    description: 'Компактное устройство в современном дизайне для ежедневного использования. Эргономичный корпус и удобное управление. Подходит для дома и поездок.',
    price: 25990,
    rating: 4.4,
    image: 'images/lumo.jpg',
    images: ['images/lumo1.jpg', 'images/lumo2.jpg', 'images/lumo3.jpg'],
    link: 'https://kaspi.kz/shop/p/lumo-aqua-x-seryi-148897809/',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 3,
    id: 8,
    name: 'Наушники Zhang Kai S25 черный',
    description: 'Беспроводные наушники с удобной посадкой и чистым звучанием. Подходят для музыки, звонков и учебы. Компактный кейс удобно носить с собой.',
    price: 6990,
    rating: 4.3,
    image: 'images/zk.jpg',
    images: ['images/zk1.jpg', 'images/zk2.jpg', 'images/zk3.jpg'],
    link: 'https://kaspi.kz/shop/p/naushniki-zhang-kai-s25-chernyi-136791864/',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 3,
    id: 9,
    name: 'Наушники Hydra Home Minor бежевый',
    description: 'Комфортные наушники для дома и работы. Сбалансированное звучание и удобная конструкция. Хороший вариант для длительного прослушивания.',
    price: 8990,
    rating: 4.5,
    image: 'images/hydra.jpg',
    images: ['images/hydra1.jpg', 'images/hydra2.jpg', 'images/hydra3.jpg'],
    link: 'https://kaspi.kz/shop/p/naushniki-hydra-home-minor-bezhevyi-120724130/',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 4,
    id: 10,
    name: 'Yasin 32E9000 81 см черный',
    description: '32-дюймовый телевизор с чётким изображением и современным дизайном. Подходит для фильмов, YouTube и ТВ. Компактный размер для комнаты или кухни.',
    price: 79990,
    rating: 4.6,
    image: 'images/tv.jpg',
    images: ['images/tv1.jpg', 'images/tv2.jpg', 'images/tv3.jpg'],
    link: 'https://kaspi.kz/shop/p/yasin-32e9000-81-sm-chernyi-101748828/',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 2,
    id: 11,
    name: 'Стекло для Apple iPhone 11 Pro Max черный',
    description: 'Защитное стекло для iPhone 11 Pro Max. Надёжно защищает экран от царапин и повреждений. Простая установка и высокая прозрачность.',
    price: 1990,
    rating: 4.6,
    image: 'images/glass.jpg',
    images: ['images/glass1.jpg', 'images/glass2.jpg', 'images/glass3.jpg'],
    link: 'https://kaspi.kz/shop/p/steklo-dlja-apple-iphone-11-pro-max-chernyi-133402149/?c=750000000',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 2,
    id: 12,
    name: 'Apple 20W USB-C Power Adapter белый',
    description: 'Оригинальный адаптер питания Apple мощностью 20W. Обеспечивает быструю и безопасную зарядку iPhone и других устройств.',
    price: 11990,
    rating: 4.9,
    image: 'images/adapter.jpg',
    images: ['images/adapter1.jpg', 'images/adapter2.jpg', 'images/adapter3.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-20w-usb-c-power-adapter-belyi-100984093/?c=750000000',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 1,
    id: 13,
    name: 'Samsung Galaxy A07 6GB/128GB черный',
    description: 'Современный смартфон Samsung с большим экраном и объёмной памятью 128 ГБ. Подходит для работы, учебы и повседневного использования.',
    price: 79990,
    rating: 4.7,
    image: 'images/galaxya07.jpg',
    images: ['images/galaxya071.jpg', 'images/galaxya072.jpg', 'images/galaxya073.jpg'],
    link: 'https://kaspi.kz/shop/p/samsung-galaxy-a07-6-gb-128-gb-chernyi-144817763/?c=750000000',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 1,
    id: 14,
    name: 'Apple iPhone 16 128GB черный',
    description: 'Смартфон Apple нового поколения с мощным процессором и ярким дисплеем. Отличная камера и высокая производительность.',
    price: 549990,
    rating: 4.9,
    image: 'images/iphone16.jpg',
    images: ['images/iphone161.jpg', 'images/iphone162.jpg', 'images/iphone163.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-iphone-16-128gb-chernyi-123713453/?c=750000000',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 1,
    id: 15,
    name: 'Apple iPhone 17 Pro Max 256GB оранжевый',
    description: 'Флагманский iPhone с увеличенным дисплеем и продвинутой камерой. Максимальная производительность и премиальный дизайн.',
    price: 749990,
    rating: 4.9,
    image: 'images/iphone17pm.jpg',
    images: ['images/iphone17pm1.jpg', 'images/iphone17pm2.jpg', 'images/iphone17pm3.jpg'],
    link: 'https://kaspi.kz/shop/p/apple-iphone-17-pro-max-256gb-oranzhevyi-145468241/?c=750000000',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 1,
    id: 16,
    name: 'Realme Note 70 6GB/128GB черный',
    description: 'Доступный смартфон с большим экраном и хорошей автономностью. Подходит для социальных сетей, видео и повседневных задач.',
    price: 69990,
    rating: 4.6,
    image: 'images/realme70.jpg',
    images: ['images/realme701.jpg', 'images/realme702.jpg', 'images/realme703.jpg'],
    link: 'https://kaspi.kz/shop/p/realme-note-70-6-gb-128-gb-chernyi-145564546/?c=750000000',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 3,
    id: 17,
    name: 'Наушники Xiaomi Redmi Buds 6 Play черный',
    description: 'Беспроводные наушники с качественным звуком и удобной посадкой. Подходят для музыки, звонков и учебы.',
    price: 14990,
    rating: 4.7,
    image: 'images/redmibuds.jpg',
    images: ['images/redmibuds1.jpg', 'images/redmibuds2.jpg', 'images/redmibuds3.jpg'],
    link: 'https://kaspi.kz/shop/p/naushniki-xiaomi-redmi-buds-6-play-chernyi-123229678/?c=750000000',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 3,
    id: 18,
    name: 'Apple EarPods USB-C белый',
    description: 'Оригинальные проводные наушники Apple с разъёмом USB-C. Чистое звучание и удобная форма для ежедневного использования.',
    price: 12990,
    rating: 4.8,
    image: 'images/earpods.jpg',
    images: ['images/earpods1.jpg', 'images/earpods2.jpg', 'images/earpods3.jpg'],
    link: 'https://kaspi.kz/shop/p/naushniki-apple-earpods-usb-c-belyi-114086432/?c=750000000',
    isFavorite: false,
  },
  {
    likes: 0,
    categoryId: 4,
    id: 19,
    name: 'Yasin 40E9000 102 см черный',
    description: '40-дюймовый телевизор с качественным изображением и современным дизайном. Подходит для фильмов, YouTube и ТВ-программ.',
    price: 109990,
    rating: 4.6,
    image: 'images/tv40.jpg',
    images: ['images/tv401.jpg', 'images/tv402.jpg', 'images/tv403.jpg'],
    link: 'https://kaspi.kz/shop/p/yasin-40e9000-102-sm-chernyi-137978460/?c=750000000',
    isFavorite: false,
  },
]
